### ISSUE TITLE
CloudFormations fails to deploy when using SNSEventSource

### ISSUE THREAD

**Issue by nbyl** [mweagle/Sparta#104]
When trying to deploy the sparta application from the attached [demo-project.zip](https://github.com/mweagle/Sparta/files/1833899/demo-project.zip), CloudFormations fails to deploy the generated stack. The deployment of the custom resource for SNS fails.

By digging through CloudWatch Logs, I found the following errors:

```
{
    "level": "error",
    "msg": "No handler found for lambdaName: demo_Custom_goAWS_SNSLambdaEventSourceResource. Known: _main_echoSNSEvent,_Custom_goAWS_HelloWorldResource,_Custom_goAWS_S3LambdaEventSourceResource,_Custom_goAWS_SNSLambdaEventSourceResource,_Custom_goAWS_SESLambdaEventSourceResource,_Custom_goAWS_CloudWatchLogsLambdaEventSourceResource,_Custom_goAWS_ZipToS3BucketResource",
    "time": "2018-03-21T15:16:35Z"
}
```

**Comment by mweagle** [comment]
HI @nbyl - thanks for the sample. I think this was introduced in move to 1.0. I've been working on 1.10 for a bit and just merged that to master. Using your sample, I updated the SNS ARN and reprovisioned successfully. Could you pull the latest and please LMK? Thanks.

**Comment by nbyl** [comment]
Using the latest master branch, it now works. Thanks.

**Comment by mweagle** [comment]
Thx - closing.
