### ISSUE TITLE
overview page is broken

### ISSUE THREAD

**Issue by tirumaraiselvan** [mweagle/Sparta#133]
https://gosparta.io/overview which is referenced in main page is broken.

**Comment by mweagle** [comment]
Thanks for the heads up @tirumaraiselvan - will be resolved in the next release.

In the meantime please visit the [updated overview](https://gosparta.io/example_service/step1/) page.

**Comment by mweagle** [comment]
URL updated & pushed to https://gosparta.io/. Closing.
