### ISSUE TITLE
Lambda logs tail command

### ISSUE THREAD

**Issue by moshloop** [mweagle/Sparta#157]
It would be really great if Sparta had a way to live tail logs from provisioned lambdas similar to https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-logs.html

**Comment by mweagle** [comment]
Hi @moshloop. There's a version of this via http://gosparta.io/cli_options/#explore , but that may not be what you're thinking. Are you thinking more along the lines of SAM, https://github.com/lucagrulla/cw ?

**Comment by mweagle** [comment]
Hi @moshloop  - circling back to get your thoughts on the options. Thanks!

**Comment by moshloop** [comment]
cw Is exactly what I was looking for :)  - keeping it as a separate binary is also as it follows the UNIX philosophy
