### ISSUE TITLE
Add option to bundle static files in the zip archive

### ISSUE THREAD

**Issue by ryanwalls** [mweagle/Sparta#21]
I'm looking for a way to configure my lambda functions dynamically.  In other apps I use spf13/viper to load local config files.  Because in Sparta we create a binary that doesn't include the config files, this doesn't work.  

Ideally I'd like to be able to tell Sparta that I want some files included in the zip file and unpacked along with my binary.  That way I could load them in the traditional way.  (Perhaps this could piggyback on the existing functionality for zipping up static S3 websites?)

**Comment by mweagle** [comment]
HI Ryan,
Can you use the new [archive hook](http://gosparta.io/docs/application/workflow_hooks/#archive-hook) for this?

**Comment by ryanwalls** [comment]
@mweagle Perhaps you know the answer to this... if I include a file in the zip, what is the path from which to load it from in my lambda function?

**Comment by ryanwalls** [comment]
Perhaps here?  $LAMBDA_TASK_ROOT?

**Comment by ryanwalls** [comment]
Thanks.  The archive hook will work.  Haven't implemented yet, but the example is straight forward.  Closing this.

**Comment by mweagle** [comment]
Before I closed this I was doing some local testing to confirm that it actually did what it was supposed to. I was running into some ZIP corruption issue that I think I resolved with the upcoming 0.9.1 - LMK if you encounter any problems with the existing release.
