### ISSUE TITLE
Add support for specifying IAM role/definition for API Gateway endpoints

### ISSUE THREAD

**Issue by ryanwalls** [mweagle/Sparta#22]
Seems that this might fit within the scope of this project considering that Sparta can create API Gateway resources and endpoints.  Would be nice to configure IAM at the same time.

**Comment by mweagle** [comment]
It seems reasonable, but I'm not really sure what's involved here - can you give me a bit more background?

**Comment by ryanwalls** [comment]
Yeah, just meaning that API gateway endpoints can be restricted to specific IAM roles.  More info about configuring it can be found here:  http://docs.aws.amazon.com/apigateway/latest/developerguide/permissions.html.

Not the highest priority since I can configure it in a separate step using other tools like ansible or the aws cli.

**Comment by mweagle** [comment]
Hi @ryanwalls - realize this issue has gone stale. Is this something you'd still like to see? TIA for the feedback.

**Comment by ryanwalls** [comment]
@mweagle I think separation of concerns is good.  I can use a separate tool to configure API gateway endpoints after they've been created.  

Also, just a point of feedback, we've stopped using Sparta, but just because we have a future need to run completely offline, so reliance on AWS Lambda is not an option right now.  But great project!
