### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by h12w** [mweagle/Sparta#30]
I'm trying to run a CloudWatch cron job in Lambda, after the job is completed (I can tell from the log), the Lambda function fails with the error message below:

```json
{
  "errorMessage": "socket hang up",
  "errorType": "Error",
  "stackTrace": [
    "createHangUpError (_http_client.js:200:15)",
    "Socket.socketOnEnd (_http_client.js:285:23)",
    "emitNone (events.js:72:20)",
    "Socket.emit (events.js:166:7)",
    "endReadableNT (_stream_readable.js:905:12)",
    "nextTickCallbackWith2Args (node.js:437:9)",
    "process._tickDomainCallback (node.js:392:17)"
  ]
}
```

It seems an error from Node.js. Any ideas?

**Comment by mweagle** [comment]
It's hard to tell from just this error message, but is it possible that the Go function isn't writing a response to `http.ResponseWriter` as in:

```
// Standard AWS λ function
func helloWorld(event *json.RawMessage,
	context *sparta.LambdaContext,
	w http.ResponseWriter,
	logger *logrus.Logger) {
       
       // Job logic

	fmt.Fprint(w, "Job complete")
}
```

**Comment by h12w** [comment]
It seems to be a 10-seconds timeout in the Node.js part. To reproduce this issue, use the code below:

```go
func helloWorld(event *json.RawMessage,
    context *sparta.LambdaContext,
    w http.ResponseWriter,
    logger *logrus.Logger) {

    time.Sleep(11 *time.Second)
}
```

**Comment by mweagle** [comment]
Thanks for the details - investigating.

**Comment by h12w** [comment]
### [workaround]
I cannot wait for the fix, so I have switched to [eawsy/aws-lambda-go](https://github.com/eawsy/aws-lambda-go). It does not provide CloudWatch triggers but the deployment is a lot faster than Sparta.

**Comment by mweagle** [comment]
Appreciate the update - I still would like to resolve this issue, but need some additional diagnostic information. If you do end up switching back to Sparta, please re-open.
