### ISSUE TITLE
Custom resources make Cloudformation time out

### ISSUE THREAD

**Issue by inge4pres** [mweagle/Sparta#46]
Hi,

I'm trying to deploy an API Gateway attached to a S3 website with CORS; then I have other functions making use of S3 bucket as event source for Lambda functions. The Cloudformation stack that is created with

`myspartaapp provision --s3Bucket myspartabucket `

fails to stabilize with error

```
AWS::CloudFormation::CustomResource   S3SiteBuilder868e68ba5c700a3b62c6e516eb71c2cf8e814871	Resource creation cancelled
AWS::CloudFormation::CustomResource   ConfigS363904f6fbd39013d6c82dd26d828dcbc950f26db	Resource creation cancelled
AWS::CloudFormation::Stack	myspartaapp   Stack creation time exceeded the specified timeout. Delete requested by user.
```

Sparta version 
GoVersion=go1.7.5 LinkFlags= Option=version SpartaVersion=0.10.0 

My code is like

```
func businessLogic(api *sparta.API) []*sparta.LambdaAWSInfo {
	var funcs []*sparta.LambdaAWSInfo
        //Function to get event from S3 bucket, no API Gateway mapping for it
        // the S3 bucket is only declared as string, no object definition for it and it does not exist

        //Functions to process events from API Gateway

        return funcs
}

func main() {
	//Create API Gateway
	apiStage := sparta.NewStage("v1")
	apiGateway := sparta.NewAPIGateway("myspartaapp", apiStage)
	apiGateway.CORSEnabled = true

	//Create S3 static website
	s3Site, err := sparta.NewS3Site("./static")
	if err != nil {
                log.Errorf("%v", err)
		os.Exit(1)
	}

	// Deploy it
	sparta.Main("myspartaapp",
		"My Sparta application",
		businessLogic(apiGateway),
		apiGateway,
		s3Site)
}
```

Sparta output log

```
time="2017-02-26T18:54:24+01:00" level=error msg="Stack provisioning error"
time="2017-02-26T18:54:24+01:00" level=error msg="\tError ensuring AWS::CloudFormation::Stack (myspartaapp): The following resource(s) failed to delete: [ConfigS363904f6fbd39013d6c82dd26d828dcbc950f26db, S3SiteBuilder868e68ba5c700a3b62c6e516eb71c2cf8e814871]. "
time="2017-02-26T18:54:24+01:00" level=error msg="\tError ensuring AWS::CloudFormation::CustomResource (S3SiteBuilder868e68ba5c700a3b62c6e516eb71c2cf8e814871): Custom Resource failed to stabilize in expected time"
time="2017-02-26T18:54:24+01:00" level=error msg="\tError ensuring AWS::CloudFormation::CustomResource (ConfigS363904f6fbd39013d6c82dd26d828dcbc950f26db): Custom Resource failed to stabilize in expected time"
time="2017-02-26T18:54:24+01:00" level=error msg="\tError ensuring AWS::CloudFormation::CustomResource (ConfigS363904f6fbd39013d6c82dd26d828dcbc950f26db): Resource creation cancelled"
time="2017-02-26T18:54:24+01:00" level=error msg="\tError ensuring AWS::CloudFormation::CustomResource (S3SiteBuilder868e68ba5c700a3b62c6e516eb71c2cf8e814871): Resource creation cancelled"
```

Any idea?
Thank you

**Comment by mweagle** [comment]
Hi @inge4pres - thanks for the report. Have you had a chance to see if this also happens with https://github.com/mweagle/SpartaHTML? I'll take a look - thanks.

**Comment by mweagle** [comment]
@inge4pres  - I can think of a couple of explanations but need a bit more information from AWS to diagnose the error. 

There should be a CloudWatch log group entry of the form _/aws/lambda/*-S3SiteCreator*_ with more information about the custom resource failure. Can you post/gist that content?  TIA.

**Comment by inge4pres** [comment]
Hi @mweagle  thanks for support.
Only relevant error message I can seem to find is

```
2017-02-23T07:35:49.720Z	3de5833b-f99a-11e6-a4bd-4782452938f2
{
    "msg": "time=\"2017-02-23T07:35:49Z\" level=error msg=\"provision error\" Error=\"Path does not exist: /var/task/static\" RequestType=CreateS3StaticWebsite Scope=Infrastructure "
}
```

I an thinking of this because my local directory is called "static".
Trying now to run the SpartaHTML sample app

**Comment by inge4pres** [comment]
Hi @mweagle I tried running the SpartaHTML app and it's working as expected I think
```
time="2017-03-01T09:48:06+01:00" level=info msg="Stack output" Description="S3 Website URL" Key=S3SiteURL Value="http://spartahtml-site09b75dfd6a3e4d7e2167f6eca73957ee83-xlfft3siduje.s3-website.eu-central-1.amazonaws.com"
time="2017-03-01T09:48:06+01:00" level=info msg="Stack output" Description="API Gateway URL" Key=APIGatewayURL Value="https://tb9dh8ri60.execute-api.eu-central-1.amazonaws.com/v1"
time="2017-03-01T09:48:06+01:00" level=info msg="Stack provisioned" CreationTime=2017-03-01 08:37:45.657 +0000 UTC StackId="arn:aws:cloudformation:eu-central-1:295665577671:stack/SpartaHTML/57dad610-fe5a-11e6-a1ec-500c52a6cefe" StackName=SpartaHTML
time="2017-03-01T09:48:06+01:00" level=info msg="Elapsed time" Seconds=691
time="2017-03-01T09:48:06+01:00" level=warning msg="Failed to cleanup intermediate artifact" Error="remove C:\\Users\\francesco.gualazzi\\Documents\\Software\\Golang\\src\\github.com\\mweagle\\SpartaHTML/.sparta/SpartaHTML-S3Site.zip: The system cannot find the file specified." Path="C:\\Users\\francesco.gualazzi\\Documents\\Software\\Golang\\src\\github.com\\mweagle\\SpartaHTML/.sparta/SpartaHTML-S3Site.zip"
```

**Comment by mweagle** [comment]
Hi @inge4pres - It looks as though you're running on Windows...I'm guessing there's an issue with path normalization somewhere along the way that's causing an error. When I visit your SpartaHTML site (*S3SiteURL* in the outputs - http://spartahtml-site09b75dfd6a3e4d7e2167f6eca73957ee83-xlfft3siduje.s3-website.eu-central-1.amazonaws.com/), the dependent resources fail to load:

![image](https://cloud.githubusercontent.com/assets/404458/23491088/f865ea4c-feb0-11e6-81a9-c2fcf4f1a0eb.png)

When I provision via my Mac, the CSS files are properly loaded & I see

![image](https://cloud.githubusercontent.com/assets/404458/23491113/15684356-feb1-11e6-9e35-e27547996d7f.png)

I will take a look once I can get to my Windows machine in a few days. Are you able to work around this in the meantime?

**Comment by inge4pres** [comment]
Hi @mweagle sure I'm in no hurry and If I can help fixing the bug please let me know: I still didn't have the time to review the full code of Sparta but if pinpointed to the right piece of source I think I get it done :)

**Comment by mweagle** [comment]
Hi @inge4pres - finally got the Windows machine up and running & I can reproduce. Working on a fix.

**Comment by mweagle** [comment]
ZIP filenames were inconsistently handled when building on Windows. Ensured ZIP headers are properly normalized with https://github.com/mweagle/Sparta/commit/d8d02580940e6eb8b1a46d895bc15119cee0f925.

**Comment by inge4pres** [comment]
Hi @mweagle 

confirmed. It works great with the updated code.
http://spartahtml-site09b75dfd6a3e4d7e2167f6eca73957ee83-t89lqvwrd249.s3-website.eu-central-1.amazonaws.com

Thank you for fixing :)
