### ISSUE TITLE
Properly cleanup intermediate artifacts on windows

### ISSUE THREAD

**Issue by mweagle** [mweagle/Sparta#47]
Promoted from: https://github.com/mweagle/Sparta/issues/46#issuecomment-283303004

> time="2017-03-01T09:48:06+01:00" level=warning msg="Failed to cleanup intermediate artifact" Error="remove C:\\Users\\francesco.gualazzi\\Documents\\Software\\Golang\\src\\github.com\\mweagle\\SpartaHTML/.sparta/SpartaHTML-S3Site.zip: The system cannot find the file specified." Path="C:\\Users\\francesco.gualazzi\\Documents\\Software\\Golang\\src\\github.com\\mweagle\\SpartaHTML/.sparta/SpartaHTML-S3Site.zip"

/cc @inge4pres

**Comment by inge4pres** [comment]
I suppose this is where it's getting stuck

provision.go:838
`ctx.registerFileCleanupFinalizer(tmpFile.Name())`

is using 

provision_utils.go:66
`temporaryPath := path.Join(buildDir, name)`

probably `filepath.Join` would be more portable?

**Comment by inge4pres** [comment]
Using `filepath` as in previous comment is not fixing the issue, still no zip created into `\\.sparta\\`

**Comment by mweagle** [comment]
Resolved by https://github.com/mweagle/Sparta/commit/87b4bb1c770a4f165f0726b841e6fef266aca42a.

**Comment by mweagle** [comment]
Marking closed - please reopen if the issue persists for you.
