### ISSUE TITLE
Cloud formation update stuck then failed - no events in log

### ISSUE THREAD

**Issue by jbrook** [mweagle/Sparta#5]
I had some issues with a Cloudformation update that got stuck in the update state after I upgraded to the latest master code of Sparta. I was impatient and cancelled it. Then it got stuck in the rollback state. I manually deleted the resources and then changed my serviceName and ran Sparta `provision` again. That also seemed to get stuck in the update state for about an hour and eventually failed. However it was deleted before I ever got to see any events. The first rollback eventually completed and I was able to provision from scratch. Do you think it's possible for a Cloudformation update to fail without any events? I am bit worried that I have no way of knowing what happened. Here is the output I got from Sparta - is it possible that it's missing something?

```
INFO[1109] Current state: CREATE_IN_PROGRESS
DEBU[1139] AWS Request                                   Method=POST Operation=DescribeStacks Path=/ Payload={
  StackName: "arn:aws:cloudformation:eu-west-1:XXX"
} Service=cloudformation
INFO[1139] Current state: CREATE_IN_PROGRESS
DEBU[1169] AWS Request                                   Method=POST Operation=DescribeStacks Path=/ Payload={
  StackName: "arn:aws:cloudformation:eu-west-1:XXX"
} Service=cloudformation
INFO[1169] Current state: DELETE_IN_PROGRESS
DEBU[1199] AWS Request                                   Method=POST Operation=DescribeStacks Path=/ Payload={
  StackName: "arn:aws:cloudformation:eu-west-1:XXX"
} Service=cloudformation
INFO[1200] Current state: DELETE_COMPLETE
DEBU[1200] AWS Request                                   Method=POST Operation=DescribeStackEvents Path=/ Payload={
  StackName: "arn:aws:cloudformation:eu-west-1:XXX"
} Service=cloudformation
ERRO[1200] Stack provisioning failed.
ERRO[1200] Failed to provision: MyServiceName
INFO[1200] Attempting to cleanup ZIP archive: MyServiceName565990549
DEBU[1200] AWS Request                                   Method=DELETE Operation=DeleteObject Path=/{Bucket}/{Key+} Payload={
  Bucket: "xxxxx-sparta-provisioning",
  Key: "MyServiceName565990549"
} Service=s3
ERRO[1200] Failed to provision: MyServiceName
```

**Comment by mweagle** [comment]
> Do you think it's possible for a Cloudformation update to fail without any events?

In the process of implementing [S3 sites](http://gosparta.io/docs/s3site/) I was seeing corrupt ZIP archives being created.  The error was intermittent and I suspect input sensitive.  The failure pattern is similar to what you described.  

There are a couple of other places to check for info:
  * CloudWatch logs for the lambda function(s) that are invoked during stack provisioning.  In my case, an exception wasn't being properly handled which caused a timeout/rollback situation. 
  * [CloudTrail](https://aws.amazon.com/cloudtrail/)

If you're still seeing this issue, could you check those locations to see if there is more information?  

>  I am bit worried that I have no way of knowing what happened.

I agree - it must always be possible to determine why a provisioning failure occurred.

**Comment by mweagle** [comment]
@jbrook - I'm going to provisionally close this due to inactivity.  Please re-open if you're still running into issues.
