### ISSUE TITLE
Support non-destructive APIGateway updates

### ISSUE THREAD

**Issue by mweagle** [mweagle/Sparta#6]
API gateway updates are currently done via `delete` then `create` during an _UPDATE_ request.  This causes a new REST API to be created, which results in unstable hostnames across stack updates.

> @mweagle thanks! Is it the Sparta or AWS that creates a new URI for the API for every deployment?

/cc @seiffert

**Comment by mweagle** [comment]
Working on this - fix to be available in `0.5.3` release.

**Comment by seiffert** [comment]
Awesome! Really looking forward to this!

**Comment by mweagle** [comment]
@seiffert  - Addressed with `0.5.3` - please reopen if you run into issues.  Thanks.
