### ISSUE TITLE
add ability to use attached methods as a lambda handler

### ISSUE THREAD

**Issue by sullirobert** [mweagle/Sparta#8]
I’m running into trouble with Registering lambda functions where the registered lambda function is a func attached to a struct. The issues seems be causing cloudFormation to reject the template due to the lambda function name.

here is my deploy log output, 

INFO[0010] Registering Sparta function                   FunctionName=github.com/Scotts-Marketplace/smpb/marketplace/infrastructure/serverless.(*LambdaServer).HandleRequest-fm
...
ERRO[0017] ValidationError: Template format error: Resource name githubcom/ScottsMarketplace/smpb/marketplace/infrastructure/serverless(*LambdaServer)HandleRequestfmLambda443fd5f4645d1e4b1a7bb60f0ae87f3398dabac1 is non alphanumeric.

as you can see,  "(*LambdaServer)” is getting added automatically, and contains the bad chars

**Comment by mweagle** [comment]
@sullirobert - Thanks for the report.  Addressed with `0.5.1` - please reopen if you encounter issues.
