### ISSUE TITLE
Support custom domains

### ISSUE THREAD

**Issue by mweagle** [mweagle/Sparta#91]
Add support for API-gateway [custom domains](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html). Should include a corresponding demo project as well.

**Comment by mweagle** [comment]
👀

**Comment by mweagle** [comment]
Related: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-domainname.html

**Comment by simonfrey** [comment]
For HTTPs Support this is also to be condsidered:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html

**Comment by mweagle** [comment]
Yep. I think that can be pulled through via the cert [Ref](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html) as a value for the [CertificateArn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-domainname.html#cfn-apigateway-domainname-certificatearn) ?

**Comment by mweagle** [comment]
Available with [1.9.2](https://github.com/mweagle/Sparta/blob/master/CHANGES.md#v192---the-names-edition-). Closing.
